import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import signs from '../pairs-data/signs.json'
import { Sign } from '@/components/Sign'
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/scss';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const sliderBreakpoints = {
    768: {
      slidesPerView: 5
    },
    1200: {
      slidesPerView: 7
    }
  }


  return (
    <>
      <Head>
        <title>Zodiac queer compatibility calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <h1 className={styles.pageTitle}>Will it be a match 🌟?</h1>
        <h2 className={styles.subtitle}>Check your zodiac compatibility</h2>
        <p className={styles.description}>Looking for the perfect match? Our zodiac partnership compatibility test uses the power of astrology to help you. Fiscover which zodiac signs are most compatible with yours. Whether you're looking for a romantic partner or just a new friend, our comparison provides valuable insights and advantages to help you make the most of your relationships.</p>
        
        <h3 className={styles.sliderTitle}>Your sign</h3>

        <Swiper
          slidesPerView={3}
          centeredSlides
          spaceBetween={50}
          loop
          slideToClickedSlide
          breakpoints={sliderBreakpoints}>
          {signs.map(sign =>
            <SwiperSlide key={sign.name}>
              <Sign signInfo={sign} />
            </SwiperSlide>)}
        </Swiper>

        <span className={styles.plus}>+</span>
        <h3 className={styles.sliderTitle}>Their sign</h3>

        <Swiper
          slidesPerView={3}
          centeredSlides
          spaceBetween={50}
          loop
          slideToClickedSlide
          breakpoints={sliderBreakpoints}>
          {signs.map(sign =>
            <SwiperSlide key={sign.name}>
              <Sign signInfo={sign} />
            </SwiperSlide>)}
        </Swiper>

        <button className={styles.submit}>Check your compatibility✨</button>
      </main>
    </>
  )
}
