import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import signs from '../pairs-data/signs.json'
import { Sign } from '@/components/Sign'
import { Carousel } from '@trendyol-js/react-carousel'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Zodiac queer compatibility calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <h1 className={styles.pageTitle}>Will it be a match <span>☀🌟</span>?</h1>
        <h2 className={styles.subtitle}>Check your zodiac compatibility</h2>
        <p className={styles.description}>Looking for the perfect match? Our zodiac partnership compatibility test uses the power of astrology to help you. Fiscover which zodiac signs are most compatible with yours. Whether you're looking for a romantic partner or just a new friend, our comparison provides valuable insights and advantages to help you make the most of your relationships.</p>

        <Carousel show={5} slide={1} infinite swiping useArrowKeys leftArrow={null} rightArrow={null}>
          {signs.map(sign => <Sign key={sign.name} signInfo={sign} />)}
        </Carousel>

        <h2 className={styles.plus}>+</h2>
        <h2 className={styles.subtitle}>Their sign</h2>

        <section className={styles.slider}>
          {signs.map(sign => <Sign key={sign.name} signInfo={sign} />)}
        </section>

        <button className={styles.submit}>Check your compatibility✨</button>
      </main>
    </>
  )
}
